# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qr < Formula
  desc "Generate and read QR codes from the terminal."
  homepage "https://github.com/julian0xff/qr"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/julian0xff/qr/releases/download/v0.1.0/qr_0.1.0_darwin_amd64.tar.gz"
      sha256 "9fe1d411b473c77b3633ee0d6c5f32a0b4760703a1526a84cf223c926c334f7d"

      define_method(:install) do
        bin.install "qr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/julian0xff/qr/releases/download/v0.1.0/qr_0.1.0_darwin_arm64.tar.gz"
      sha256 "85d787e186ab594fbafc1f8802d27dc3151f8673375d3b0c40f760cc900e8689"

      define_method(:install) do
        bin.install "qr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/julian0xff/qr/releases/download/v0.1.0/qr_0.1.0_linux_amd64.tar.gz"
      sha256 "30197bbc3e3aa2999bfd28bc9b8dea2960631f98800a66059aaf84671f935f33"
      define_method(:install) do
        bin.install "qr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/julian0xff/qr/releases/download/v0.1.0/qr_0.1.0_linux_arm64.tar.gz"
      sha256 "cf7903079ce1406c663e063caa2840c63155aa7dfb398f11019cedaba2f88bec"
      define_method(:install) do
        bin.install "qr"
      end
    end
  end

  test do
    system "#{bin}/qr", "--version"
  end
end
