# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Save < Formula
  desc "Save articles for reading later — from the terminal."
  homepage "https://github.com/julian0xff/save"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/julian0xff/save/releases/download/v0.1.0/save_0.1.0_darwin_amd64.tar.gz"
      sha256 "56eab75e35e68500d17c59c5e3bf9914f78c632ca659f6de948e3421aaa5550a"

      define_method(:install) do
        bin.install "save"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/julian0xff/save/releases/download/v0.1.0/save_0.1.0_darwin_arm64.tar.gz"
      sha256 "e031a77c617ab7ca2f302628173c62e59f6dbb482fea06dc8dd1cf1191f1ceb1"

      define_method(:install) do
        bin.install "save"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/julian0xff/save/releases/download/v0.1.0/save_0.1.0_linux_amd64.tar.gz"
      sha256 "bdba20c25ad2444b5dfa2df3587bdbc549a5559b3976262717b45590f36c934e"
      define_method(:install) do
        bin.install "save"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/julian0xff/save/releases/download/v0.1.0/save_0.1.0_linux_arm64.tar.gz"
      sha256 "296a4fb03f08ad63d1da0e9bfa333eaffb800f263ca7a36d49fb145116449582"
      define_method(:install) do
        bin.install "save"
      end
    end
  end

  test do
    system "#{bin}/save", "--version"
  end
end
